using System;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Diagnostics;
using System.Drawing;
using System.Windows.Forms;
using System.Collections.Generic;
using System.Threading.Tasks;
using System.Web.Script.Serialization;

namespace ComfyDrop {
public class Entry { public string name; public bool dir; public long size; public string modified; }
public class Settings { public string Host="", User="root", Port="22", Key="", Remote="/workspace/ComfyUI/output", Destination="", Cli="runpodctl.exe"; }
public partial class MainWindow : Form {
    TextBox host=new TextBox(), user=new TextBox(), port=new TextBox(), key=new TextBox(), remote=new TextBox(), dest=new TextBox(), cli=new TextBox(), code=new TextBox(), filter=new TextBox();
    ListView files=new ListView(); RichTextBox log=new RichTextBox(); Label status=new Label();
    Button browse, download, receive, cancel; ProgressBar progress=new ProgressBar();
    List<Process> processes=new List<Process>(); List<Entry> entries=new List<Entry>();
    bool busy=false, cancelled=false; string listedPath="", lastFolder="";
    string config=Path.Combine(ProfileStore.DirectoryPath,"settings.json");
    JavaScriptSerializer json=new JavaScriptSerializer();
    TableLayoutPanel mainLayout; Button settingsButton, consoleButton;
    bool consoleExpanded;
    public MainWindow() {
        Text="ComfyDrop 1.1 | RunPod output downloader"; Size=new Size(1080,780); MinimumSize=new Size(950,650); StartPosition=FormStartPosition.CenterScreen;
        Font=new Font("Segoe UI",10); BackColor=Color.FromArgb(244,246,250);
        mainLayout=new TableLayoutPanel { Dock=DockStyle.Fill, Padding=new Padding(24), ColumnCount=1, RowCount=6 };
        mainLayout.RowStyles.Add(new RowStyle(SizeType.Absolute,65)); mainLayout.RowStyles.Add(new RowStyle(SizeType.Percent,100));
        mainLayout.RowStyles.Add(new RowStyle(SizeType.Absolute,42)); mainLayout.RowStyles.Add(new RowStyle(SizeType.Absolute,0));
        mainLayout.RowStyles.Add(new RowStyle(SizeType.Absolute,30)); mainLayout.RowStyles.Add(new RowStyle(SizeType.Absolute,8)); Controls.Add(mainLayout);
        var header=new TableLayoutPanel { Dock=DockStyle.Fill,ColumnCount=2 };header.ColumnStyles.Add(new ColumnStyle(SizeType.Percent,100));header.ColumnStyles.Add(new ColumnStyle(SizeType.Absolute,125));
        header.Controls.Add(new Label { Text="ComfyDrop", Font=new Font("Segoe UI",24,FontStyle.Bold), AutoSize=true });
        settingsButton=Button("Settings…",delegate {ShowSettings();});settingsButton.Margin=new Padding(3,12,3,3);header.Controls.Add(settingsButton); mainLayout.Controls.Add(header,0,0);
        var tabs=new TabControl { Dock=DockStyle.Fill }; mainLayout.Controls.Add(tabs,0,1);
        var sshTab=new TabPage("Browse ComfyUI outputs") { Padding=new Padding(12),BackColor=Color.White }; tabs.TabPages.Add(sshTab);
        var ssh=new TableLayoutPanel { Dock=DockStyle.Fill, ColumnCount=1, RowCount=4 }; ssh.RowStyles.Add(new RowStyle(SizeType.Absolute,40));ssh.RowStyles.Add(new RowStyle(SizeType.Absolute,36));ssh.RowStyles.Add(new RowStyle(SizeType.Percent,100));ssh.RowStyles.Add(new RowStyle(SizeType.Absolute,46));sshTab.Controls.Add(ssh);
        var pathRow=Row();pathRow.Controls.Add(new Label {Text="Output folder",AutoSize=true},0,0);remote.Dock=DockStyle.Fill;pathRow.Controls.Add(remote,1,0);browse=Button("Load folder",async delegate { await Browse(); });pathRow.Controls.Add(browse,2,0);ssh.Controls.Add(pathRow);
        var searchRow=new FlowLayoutPanel {Dock=DockStyle.Fill};searchRow.Controls.Add(new Label {Text="Filter",AutoSize=true,Margin=new Padding(3,6,6,0)});filter.Width=250;filter.TextChanged+=delegate {Render();};searchRow.Controls.Add(filter);searchRow.Controls.Add(new Label {Text="Double-click a folder to open it. Select files or folders to download.",AutoSize=true,Margin=new Padding(10,6,0,0)});ssh.Controls.Add(searchRow);
        files.Dock=DockStyle.Fill;files.View=View.Details;files.FullRowSelect=true;files.MultiSelect=true;files.HideSelection=false;files.Columns.Add("Name",400);files.Columns.Add("Size",110);files.Columns.Add("Modified (pod time)",180);files.DoubleClick+=async delegate {if(!busy&&files.SelectedItems.Count==1) {var e=(Entry)files.SelectedItems[0].Tag;if(e.dir){remote.Text=Join(listedPath,e.name);await Browse();}}};ssh.Controls.Add(files);
        var actions=new FlowLayoutPanel {Dock=DockStyle.Fill};actions.Controls.Add(Button("Parent folder",async delegate {if(!busy){remote.Text=ParentFolder(remote.Text);await Browse();}}));download=Button("Download selected",async delegate {await Download(false);});download.Width=165;actions.Controls.Add(download);var all=Button("Download this folder",async delegate {await Download(true);});all.Width=180;actions.Controls.Add(all);ssh.Controls.Add(actions);
        var codeTab=new TabPage("Receive with a code") {Padding=new Padding(20),BackColor=Color.White};tabs.TabPages.Add(codeTab);
        var codes=new TableLayoutPanel {Dock=DockStyle.Top,ColumnCount=1,RowCount=6,AutoSize=true}; codeTab.Controls.Add(codes);
        codes.Controls.Add(new Label { Text="No SSH setup needed",Font=new Font("Segoe UI",15,FontStyle.Bold),AutoSize=true,Margin=new Padding(0,0,0,16)});
        codes.Controls.Add(new Label { Text="1. In your pod's terminal, run the command below. Keep it running.\n2. Copy the transfer code it prints.\n3. Paste the code here and click Receive.",AutoSize=true,Margin=new Padding(0,0,0,16)});
        var copy=Button("Copy send command for output folder",delegate {try{Clipboard.SetText("runpodctl send "+ShellQuote(ValidateRemote(remote.Text)));Log("Send command copied. Paste it into your pod terminal.");}catch(Exception ex){Error(ex);}});copy.Width=340;codes.Controls.Add(copy);
        code.Width=460;code.Margin=new Padding(0,20,0,10);codes.Controls.Add(code);receive=Button("Receive files",async delegate {await ReceiveCode();});receive.Width=160;codes.Controls.Add(receive);
        codes.Controls.Add(new Label {Text="Downloads go directly to the folder chosen in Settings. Folders may arrive as ZIP files.\nThe sender must stay running until the download finishes.",AutoSize=true,Margin=new Padding(0,20,0,0)});
        var utility=new FlowLayoutPanel {Dock=DockStyle.Fill}; cancel=Button("Cancel operation",delegate {Stop();});cancel.Enabled=false;cancel.Width=145;utility.Controls.Add(cancel);var open=Button("Open downloads",delegate {try {string p=Directory.Exists(lastFolder)?lastFolder:dest.Text;if(!Directory.Exists(p))throw new Exception("Choose an existing download folder in Settings first.");Process.Start("explorer.exe",Arg(p));} catch(Exception ex){Error(ex);} });open.Width=145;utility.Controls.Add(open);
        consoleButton=Button("Show console",delegate {SetConsole(!consoleExpanded);});consoleButton.Width=140;utility.Controls.Add(consoleButton);mainLayout.Controls.Add(utility,0,2);
        log.Dock=DockStyle.Fill;log.ReadOnly=true;log.BackColor=Color.FromArgb(24,31,45);log.ForeColor=Color.FromArgb(211,224,237);log.Font=new Font("Consolas",9);log.Visible=false;mainLayout.Controls.Add(log,0,3);status.Dock=DockStyle.Fill;mainLayout.Controls.Add(status,0,4);progress.Dock=DockStyle.Fill;mainLayout.Controls.Add(progress,0,5);
        try{ProfileStore.Migrate(AppDomain.CurrentDomain.BaseDirectory);}catch(Exception ex){Log("Settings migration: "+ex.Message);}
        LoadSettings();if(File.Exists(Path.Combine(AppDomain.CurrentDomain.BaseDirectory,"runpodctl.exe")))cli.Text=Path.Combine(AppDomain.CurrentDomain.BaseDirectory,"runpodctl.exe");AddNetworkTab(tabs);
        status.Text="Choose a folder and click Load folder. Connection details are in Settings.";
        Log("ComfyDrop 1.1. Settings and encrypted credentials are saved separately from the program, so updates keep them.");
        FormClosing+=delegate(object sender,FormClosingEventArgs e){if(busy&&MessageBox.Show("Cancel the active operation and close?","ComfyDrop",MessageBoxButtons.YesNo)!=DialogResult.Yes){e.Cancel=true;return;}Stop();};
    }
    void SetConsole(bool expanded){consoleExpanded=expanded;log.Visible=expanded;mainLayout.RowStyles[3].Height=expanded?140:0;consoleButton.Text=expanded?"Hide console":"Show console";}
    TableLayoutPanel Row(){var r=new TableLayoutPanel{Dock=DockStyle.Fill,ColumnCount=3};r.ColumnStyles.Add(new ColumnStyle(SizeType.Absolute,135));r.ColumnStyles.Add(new ColumnStyle(SizeType.Percent,100));r.ColumnStyles.Add(new ColumnStyle(SizeType.Absolute,115));return r;}
    void AddField(TableLayoutPanel p,string name,TextBox box,int row){p.Controls.Add(new Label{Text=name,AutoSize=true,Margin=new Padding(0,6,0,0)},0,row);box.Dock=DockStyle.Fill;p.Controls.Add(box,1,row);}
    Button Button(string text,EventHandler click){var b=new Button{Text=text,AutoSize=false,Width=120,Height=30,FlatStyle=FlatStyle.Flat,BackColor=Color.White,Cursor=Cursors.Hand};b.Click+=click;return b;}
    void PickFile(TextBox target,string pattern){using(var d=new OpenFileDialog{Filter=pattern})if(d.ShowDialog()==DialogResult.OK)target.Text=d.FileName;}
    void Log(string s){if(IsDisposed)return;log.AppendText(s+Environment.NewLine);log.SelectionStart=log.TextLength;log.ScrollToCaret();}
    void Error(Exception e){Log("ERROR: "+e.Message);SetConsole(true);status.Text="Could not complete operation — see console for details.";}
    void SetBusy(bool value,string text){busy=value;settingsButton.Enabled=!value;browse.Enabled=download.Enabled=receive.Enabled=!value;cancel.Enabled=value;status.Text=text;progress.Style=value?ProgressBarStyle.Marquee:ProgressBarStyle.Blocks; if(!value)progress.Value=0;}
    void Stop(){cancelled=true;if(networkCancel!=null)networkCancel.Cancel();lock(processes){foreach(var p in processes.ToArray())try{if(!p.HasExited)p.Kill();}catch{}}}
    void LoadSettings(){try{var s=File.Exists(config)?json.Deserialize<Settings>(File.ReadAllText(config)):new Settings();host.Text=s.Host;user.Text=s.User;port.Text=s.Port;key.Text=s.Key;remote.Text=s.Remote;cli.Text=s.Cli;dest.Text=String.IsNullOrEmpty(s.Destination)?Path.Combine((Environment.GetEnvironmentVariable("USERPROFILE") ?? AppDomain.CurrentDomain.BaseDirectory),"Downloads","ComfyDrop"):s.Destination;}catch(Exception ex){Log("Settings could not be loaded: "+ex.Message);remote.Text="/workspace/ComfyUI/output";user.Text="root";port.Text="22";cli.Text="runpodctl.exe";dest.Text=Path.Combine(AppDomain.CurrentDomain.BaseDirectory,"Downloads");}}
    void Save(){ProfileStore.Write(config,json.Serialize(new Settings{Host=host.Text,User=user.Text,Port=port.Text,Key=key.Text,Remote=remote.Text,Destination=dest.Text,Cli=cli.Text}));}
    public static string ShellQuote(string s){return "'"+s.Replace("'","'\"'\"'")+"'";}
    public static string Arg(string s){return "\""+Regex.Replace(s,@"(\\*)\""","$1$1\\\"").TrimEnd(new char[0])+new string('\\',TrailingSlashes(s))+"\"";}
    static int TrailingSlashes(string s){int n=0;for(int i=s.Length-1;i>=0&&s[i]=='\\';i--)n++;return n;}
    static string ValidateRemote(string s){if(String.IsNullOrWhiteSpace(s)||!s.StartsWith("/")||s.IndexOfAny(new[]{'\r','\n','\0'})>=0)throw new Exception("Use an absolute Linux folder path, such as /workspace/ComfyUI/output.");return s;}
    static string Join(string p,string n){return p.TrimEnd('/')+"/"+n;}
    static string ParentFolder(string p){p=p.TrimEnd('/');int i=p.LastIndexOf('/');return i<=0?"/":p.Substring(0,i);}
    List<string> SshArgs(){int n;if(!Regex.IsMatch(host.Text,@"^[a-zA-Z0-9][a-zA-Z0-9.:-]*$")||!Regex.IsMatch(user.Text,@"^[a-zA-Z0-9_][a-zA-Z0-9_-]*$")||!Int32.TryParse(port.Text,out n)||n<1||n>65535)throw new Exception("Enter a valid SSH host, user and port from RunPod's Connect panel.");var a=new List<string>{"-T","-o","BatchMode=yes","-o","StrictHostKeyChecking=yes","-o","ConnectTimeout=15","-o","ServerAliveInterval=15","-o","ServerAliveCountMax=3","-p",n.ToString()};if(!String.IsNullOrWhiteSpace(key.Text)){if(!File.Exists(key.Text))throw new Exception("SSH private key file not found.");a.Add("-i");a.Add(key.Text);}a.Add(user.Text+"@"+host.Text);return a;}
    async Task<int> Run(string exe,List<string> args,string cwd,Action<string> output,string input=null){var p=new Process();p.StartInfo=new ProcessStartInfo{FileName=exe,Arguments=String.Join(" ",args.ConvertAll(Arg).ToArray()),WorkingDirectory=cwd,UseShellExecute=false,CreateNoWindow=true,RedirectStandardOutput=true,RedirectStandardError=true,RedirectStandardInput=true};try{p.Start();lock(processes)processes.Add(p);if(input!=null)await p.StandardInput.WriteAsync(input);p.StandardInput.Close();var a=Pump(p.StandardOutput,output);var b=Pump(p.StandardError,output);await Task.WhenAll(a,b,Task.Run(()=>p.WaitForExit()));if(cancelled)throw new OperationCanceledException("Operation cancelled. Partial downloads may remain in the transfer folder.");return p.ExitCode;}finally{lock(processes)processes.Remove(p);p.Dispose();}}
    async Task Pump(StreamReader reader,Action<string> output){char[] buffer=new char[1024];int n;while((n=await reader.ReadAsync(buffer,0,buffer.Length))>0)output(new string(buffer,0,n));}
    async Task Browse(){if(busy)return;cancelled=false;SetBusy(true,"Reading output folder…");try{string path=ValidateRemote(remote.Text);var args=SshArgs();string script="import os,json,datetime\np="+json.Serialize(path)+"\nr=[]\nwith os.scandir(p) as it:\n for e in it:\n  try:\n   s=e.stat();r.append(dict(name=e.name,dir=e.is_dir(),size=s.st_size,modified=datetime.datetime.fromtimestamp(s.st_mtime).strftime('%Y-%m-%d %H:%M')))\n  except OSError: pass\nprint('COMFYDROP_JSON:'+json.dumps(r))\n";args.Add("python3 -c "+ShellQuote(script));var output=new StringBuilder();int exit=await Run("ssh.exe",args,AppDomain.CurrentDomain.BaseDirectory,s=>output.Append(s));string raw=output.ToString();int start=raw.IndexOf("COMFYDROP_JSON:");if(exit!=0||start<0)throw new Exception(raw+"\nIf this is a new host, connect once with Windows SSH and verify its fingerprint. Ensure python3 is installed on the pod.");string line=raw.Substring(start+15).Split('\n')[0].Trim();entries=json.Deserialize<List<Entry>>(line);listedPath=path;Render();Save();status.Text=entries.Count+" items in "+path;}catch(Exception ex){Error(ex);}finally{SetBusy(false,status.Text);}}
    void Render(){files.BeginUpdate();files.Items.Clear();entries.Sort((a,b)=>a.dir!=b.dir?(a.dir?-1:1):StringComparer.OrdinalIgnoreCase.Compare(a.name,b.name));foreach(var e in entries){if(e.name.IndexOf(filter.Text,StringComparison.OrdinalIgnoreCase)<0)continue;var item=new ListViewItem(e.name);item.SubItems.Add(e.dir?"Folder":SizeText(e.size));item.SubItems.Add(e.modified);item.Tag=e;files.Items.Add(item);}files.EndUpdate();}
    static string SizeText(long n){if(n>=1073741824)return(n/1073741824.0).ToString("0.0")+" GB";if(n>=1048576)return(n/1048576.0).ToString("0.0")+" MB";if(n>=1024)return(n/1024.0).ToString("0.0")+" KB";return n+" B";}
    string NewDestination(){if(String.IsNullOrWhiteSpace(dest.Text)||!Path.IsPathRooted(dest.Text))throw new Exception("Choose an absolute download folder.");string path=Path.GetFullPath(dest.Text);Directory.CreateDirectory(path);lastFolder=path;Log("Destination: "+path);return path;}
    string Cli(){string p=cli.Text.Trim();if(String.IsNullOrWhiteSpace(p))throw new Exception("Choose your runpodctl.exe file first.");if(p.IndexOfAny(new[]{'\\','/'})>=0&&!File.Exists(p))throw new Exception("runpodctl.exe was not found at the selected location.");return p;}
    async Task ReceiveCode(){if(busy)return;cancelled=false;try{string c=code.Text.Trim();if(!Regex.IsMatch(c,@"^[a-zA-Z0-9]+(?:-[a-zA-Z0-9]+)+$"))throw new Exception("Paste only the transfer code printed by runpodctl send.");string executable=Cli();string folder=NewDestination();if(!ConfirmRunpodDestination(folder))return;SetBusy(true,"Receiving files…");Save();int exit=await Run(executable,new List<string>{"receive",c},folder,Log);if(exit!=0)throw new Exception("runpodctl exited with code "+exit+". See its output above.");status.Text="Transfer finished — open downloads to view your files.";}catch(Exception ex){Error(ex);}finally{SetBusy(false,status.Text);}}
    async Task Download(bool whole){if(busy)return;cancelled=false;try{string executable=Cli();var args=SshArgs();string path=ValidateRemote(remote.Text);if(!whole&&path!=listedPath)throw new Exception("Load this folder before selecting files.");var paths=new List<string>();if(whole)paths.Add(path);else foreach(ListViewItem item in files.SelectedItems)paths.Add(Join(listedPath,((Entry)item.Tag).name));if(paths.Count==0)throw new Exception("Select one or more files or folders first.");string command="runpodctl send "+String.Join(" ",paths.ConvertAll(ShellQuote).ToArray());if(command.Length>20000)throw new Exception("Select fewer files, or download the whole folder.");args.Add(command);string folder=NewDestination();if(!ConfirmRunpodDestination(folder))return;SetBusy(true,"Starting transfer on pod…");Save();var found=new TaskCompletionSource<string>();var accumulated=new StringBuilder();Task<int> sender=Run("ssh.exe",args,folder,s=>{Log(s);accumulated.Append(s);var match=Regex.Match(accumulated.ToString(),@"\b\d+(?:-[a-zA-Z0-9]+){2,}\b");if(match.Success)found.TrySetResult(match.Value);});Task first=await Task.WhenAny(found.Task,sender);if(first==sender&&!found.Task.IsCompleted){await sender;throw new Exception("The pod did not provide a transfer code. Check the SSH and runpodctl output above.");}string c=await found.Task;status.Text="Downloading selected outputs…";int result=await Run(executable,new List<string>{"receive",c},folder,Log);if(result!=0){Stop();try{await sender;}catch{}throw new Exception("Receive failed (exit "+result+"). Partial files may remain.");}int sent=await sender;if(sent!=0)throw new Exception("Sender exited with code "+sent+". Check downloaded files.");status.Text="Transfer finished — open downloads to view your files.";}catch(Exception ex){Stop();Error(ex);}finally{SetBusy(false,status.Text);}}
    [STAThread] public static void Main(){Application.EnableVisualStyles();Application.SetCompatibleTextRenderingDefault(false);Application.Run(new MainWindow());}
}
}
